### ISSUE TITLE
Analog Video using the IO board for RGBS is dark and shifted to the right on CRT 

### ISSUE THREAD

**Issue by amoore2600** [MrX-8B/MiSTer-Arcade-AtariTetris#1] opened 2019-12-02 18:53 UTC
This looks similar to the bug  I submisted for Ninja Kun https://github.com/MrX-8B/MiSTer-Arcade-NinjaKun/issues/3 

Video is dark and shifted right for Tetris.

**Comment by MrX-8B** [comment] 2019-12-02 19:01
Thank you for the report.

I had no problem with the monitor that my analog 15KHz can be displayed, but because it is the same as Ninja-Kun's time and special resolution, it seems that there was not enough confirmation.

Check and fix it in the near future.

**Comment by MrX-8B** [comment] 2019-12-02 20:16
It's the information I need to fix, so I'd appreciate it if you could tell me.

How far is the screen shifted to the right?
Please tell me the number of dots because it is good roughly.

**Comment by amoore2600** [comment] 2019-12-02 20:24
Here are some screen shots

![DSC_0033](https://user-images.githubusercontent.com/3682337/69992501-cb738c80-1517-11ea-90ae-b7bc4506423b.JPG)

![DSC_0032](https://user-images.githubusercontent.com/3682337/69992516-d3333100-1517-11ea-9754-d21a160e86c4.JPG)

**Comment by MrX-8B** [comment] 2019-12-02 20:52
Thank you.
It's sony's master monitor, isn't it?

Many professional video equipment requires strict signals, and it may not accept rough video signals as output by arcade boards.

Maybe I can't fix it (FPS of the game and pitch of music changes), but I'll try to fix it.

**Comment by NML32** [comment] 2019-12-02 22:13
Weird, I don't have that issue (dark screen) on my Sony PVM or Sharp CRT TV via Composite or Component.

**Comment by MrX-8B** [comment] 2019-12-02 22:20
Thank you for the report.

I see. It seems to be a display dependence problem.
I appreciate the information that there is a display that is displayed without problems.

**Comment by MrX-8B** [comment] 2019-12-03 01:16
releases/Arcade-ATetrisExp0.rbf 

Try this RBF file.
I would appreciate it if you could tell me the result.

**Comment by NML32** [comment] 2019-12-03 02:22
Too far to the left. 
![IMG_0059](https://user-images.githubusercontent.com/6879399/70014817-a5ff7680-1549-11ea-92fc-1b9d1a0425a2.JPEG)
![IMG_0058](https://user-images.githubusercontent.com/6879399/70014820-a7c93a00-1549-11ea-9e34-ccb6c5a3ad9d.JPEG)

**Comment by MrX-8B** [comment] 2019-12-03 02:38
NML32, thank you very much.
What about Amoore2600's monitor?

**Comment by amoore2600** [comment] 2019-12-03 02:53
releases/Arcade-ATetrisExp0.rbf Fixes the darkness! However now the screen is a little to far to the left like MNL32's pics.

**Comment by MrX-8B** [comment] 2019-12-03 03:04
amoore2600, thank you very much.

This may require back porch setting of the video signal in OSD.
I'll think about it for a moment.

**Comment by owlnonymous** [comment] 2019-12-03 03:16
The latest exp RBF fixed some curvature I was seeing at the top with the initial RBF. I can confirm the signal is a bit pushed to the left. Excited about this release! Thanks!

**Comment by MrX-8B** [comment] 2019-12-03 03:24
owlnonymous, thank you very much.

I also changed the timing of V-Sync a little.

**Comment by MrX-8B** [comment] 2019-12-06 23:27
releases/Arcade-ATetrisExp1.rbf

Try this RBF file.
The display position can be adjusted in "Analog Video H-Pos" of the OSD item.
I would appreciate it if you could tell me the result.

**Comment by amoore2600** [comment] 2019-12-07 01:22
This worked great! I wish every core had this.
![IMG_20191206_201635](https://user-images.githubusercontent.com/3682337/70366547-1538db80-1866-11ea-9e34-5fb2ed822247.jpg)
![IMG_20191206_201627](https://user-images.githubusercontent.com/3682337/70366550-18cc6280-1866-11ea-8f5e-7f16d87cbdd3.jpg)

**Comment by NML32** [comment] 2019-12-07 03:29
I can also confirm your OSD H-POS adjustment worked. 
H-POS value 5 is what I'm using.

**Comment by MrX-8B** [comment] 2019-12-07 03:46
Thank you guys.
I will officially release the one that implemented this feature.

**Comment by MrX-8B** [comment] 2019-12-07 04:07
Now that I've released, I'll close this issue.
Thank you, everyone.

**Closed as completed by MrX-8B** 2019-12-07 04:07 UTC
